version: '3'
services:
  cee-api:
    ports:
      - "5000:5000"
    image:
      willnx/vlab-cee-api
    environment:
      - VLAB_URL=https://localhost
      - INF_VCENTER_SERVER=virtlab.igs.corp
      - INF_VCENTER_USER=Administrator@vsphere.local
      - INF_VCENTER_PASSWORD=1.Password
    volumes:
      - ./vlab_cee_api:/usr/lib/python3.8/site-packages/vlab_cee_api
    command: ["python3", "app.py"]

  cee-worker:
    image:
      willnx/vlab-cee-worker
    volumes:
      - ./vlab_cee_api:/usr/lib/python3.8/site-packages/vlab_cee_api
      - /home/willhn/code/vlab/vlab_inf_common/vlab_inf_common:/usr/lib/python3.6/site-packages/vlab_inf_common
      - /mnt/raid/images/cee:/images:ro
    environment:
      - INF_VCENTER_SERVER=virtlab.igs.corp
      - INF_VCENTER_USER=Administrator@vsphere.local
      - INF_VCENTER_PASSWORD=1.Password
      - INF_VCENTER_TOP_LVL_DIR=/vlab

  cee-broker:
    image:
      rabbitmq:3.7-alpine
